'use client';
import { useEffect, useState, useRef } from 'react';
import type { FormEvent } from 'react';
import Link from 'next/link';
import { defaults, eventDefaults, type Settings, type EventDetails, type GalleryItem, type Rsvp, type Wish } from '@/lib/defaults';
import Icon from './Icon';
type Data={settings:Settings;event:EventDetails;gallery:GalleryItem[];rsvps:Rsvp[];wishes:Wish[]};
const tabs=[['overview','نظرة عامة'],['settings','نصوص الدعوة'],['event','التاريخ والوقت'],['location','الموقع'],['music','الموسيقى'],['gallery','الصور'],['rsvp','الحضور'],['wishes','التهاني'],['appearance','المظهر']];
const labels:Partial<Record<keyof Settings,string>>={firstName:'الاسم العربي الأول',secondName:'الاسم العربي الثاني',firstEnglish:'الاسم الإنجليزي الأول',secondEnglish:'الاسم الإنجليزي الثاني',monogram:'الحروف المختصرة',occasion:'عنوان المناسبة',introTitle:'عنوان شاشة الظرف',introText:'نص شاشة الظرف',openLabel:'زر فتح الدعوة',bismillah:'البسملة',cardText:'نص بطاقة الدعوة',eventText:'نص تفاصيل الحفل',menLabel:'عنوان موعد الرجال',womenLabel:'عنوان موعد النساء',countdownTitle:'عنوان العد التنازلي',countdownFinished:'رسالة انتهاء العد',rsvpTitle:'عنوان تأكيد الحضور',rsvpSubtitle:'نص تأكيد الحضور',rsvpSuccess:'رسالة قبول الحضور',rsvpDeclined:'رسالة الاعتذار',wishesTitle:'عنوان التهاني',wishesSubtitle:'نص التهاني',galleryTitle:'عنوان الصور',finalTitle:'عنوان البطاقة الختامية',finalText:'النص الختامي',endingText:'النهاية السينمائية'};
async function api(path:string,body:unknown){const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر إتمام العملية');return data;}
export default function Admin({loggedIn}:{loggedIn:boolean}) {
 const [auth,setAuth]=useState(loggedIn),[tab,setTab]=useState('overview'),[data,setData]=useState<Data|null>(null),[settings,setSettings]=useState(defaults),[event,setEvent]=useState(eventDefaults);
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[filter,setFilter]=useState('all');
 const [drag,setDrag]=useState<number|null>(null),[loginError,setLoginError]=useState(''); const fileInput=useRef<HTMLInputElement>(null);
 async function refresh(){const response=await fetch('/api/admin');if(response.status===401){setAuth(false);return;}if(!response.ok)throw new Error('تعذر تحميل البيانات');const result=await response.json();setData(result);setSettings(result.settings);setEvent(result.event);}
 useEffect(()=>{if(auth)refresh().catch(err=>setError(err.message));},[auth]);
 async function run(action:()=>Promise<unknown>,success='تم الحفظ بنجاح'){setBusy(true);setError('');setNotice('');try{await action();await refresh();setNotice(success);}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
 async function login(event:FormEvent<HTMLFormElement>){event.preventDefault();const fields=new FormData(event.currentTarget);setBusy(true);setLoginError('');try{await api('login',{username:fields.get('username'),password:fields.get('password')});setAuth(true);}catch(err){setLoginError((err as Error).message);}finally{setBusy(false);}}
 function setting<K extends keyof Settings>(key:K,value:Settings[K]){setSettings(old=>({...old,[key]:value}));}
 async function upload(file:File,kind:'image'|'music',target?:string){if(kind==='image'){
 if(file.size>10*1024*1024)throw new Error('حجم الصورة يجب ألا يتجاوز 10MB');
 const bitmap=await createImageBitmap(file);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw new Error('أبعاد الصورة كبيرة جدًا');}
 const scale=Math.min(1,1600/bitmap.width,1600/bitmap.height);const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('تعذر معالجة الصورة')),'image/webp',0.84));file=new File([blob],'image.webp',{type:blob.type});
 }const form=new FormData();form.set('file',file);form.set('kind',kind);if(target)form.set('target',target);const response=await fetch('/api/admin/upload',{method:'POST',body:form});const result=await response.json();if(!response.ok)throw new Error(result.error);return result;}
 async function reorder(id:number,direction:number){if(!data)return;const ids=data.gallery.map(x=>x.id);const i=ids.indexOf(id),j=i+direction;if(j<0||j>=ids.length)return;[ids[i],ids[j]]=[ids[j],ids[i]];await run(()=>api('admin/gallery',{action:'reorder',ids}),'تم ترتيب الصور');}
 function dropImage(id:number){if(drag===null||!data||id===drag)return;const ids=data.gallery.map(x=>x.id);ids.splice(ids.indexOf(drag),1);ids.splice(ids.indexOf(id),0,drag);setDrag(null);run(()=>api('admin/gallery',{action:'reorder',ids}),'تم ترتيب الصور');}
 const total=data?.rsvps.filter(x=>x.attending).reduce((sum,x)=>sum+x.guests,0)||0;
 const date=(value:string)=>new Intl.DateTimeFormat('ar',{dateStyle:'short',timeStyle:'short'}).format(new Date(value));
 const saveSettings=(event:FormEvent)=>{event.preventDefault();run(()=>api('admin/settings',settings));};
 if(!auth)return <main className="admin-login"><div className="login-card"><div className="admin-monogram" dir="ltr">A &amp; S</div><Icon name="leaf" size={32}/><h1>إدارة الدعوة</h1><p>مرحبًا بكما في مساحة فرحتكما</p><form onSubmit={login}><label htmlFor="admin-user">اسم المستخدم<input id="admin-user" name="username" required autoComplete="username" dir="ltr"/></label><label htmlFor="admin-pass">كلمة المرور<input id="admin-pass" name="password" type="password" required autoComplete="current-password" dir="ltr"/></label>{loginError&&<p className="form-error" role="alert">{loginError}</p>}<button className="primary" disabled={busy}>{busy?'جارٍ الدخول…':'تسجيل الدخول'}</button></form><Link href="/" className="text-button">العودة إلى الدعوة</Link></div></main>;
 return <main className="admin-layout"><aside className="admin-sidebar"><div className="admin-brand"><span dir="ltr">A &amp; S</span><h1>إدارة الدعوة</h1></div><nav aria-label="لوحة التحكم">{tabs.map(([id,label])=><button key={id} className={id===tab?'active':''} onClick={()=>{setTab(id);setNotice('');setError('');}}>{label}</button>)}</nav><Link href="/" target="_blank">معاينة الدعوة ↗</Link><button className="logout" onClick={()=>run(async()=>{await api('logout',{});setAuth(false);})}>تسجيل الخروج</button></aside>
  <section className="admin-content"><header className="admin-heading"><div><span>عبدالله &amp; سنا</span><h2>{tabs.find(x=>x[0]===tab)?.[1]}</h2></div><button className="admin-secondary" disabled={busy} onClick={()=>run(refresh,'تم تحديث البيانات')}>تحديث</button></header>{notice&&<p role="status" className="admin-notice">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}{!data?<p>جارٍ تحميل البيانات…</p>:<>
  {tab==='overview'&&<><div className="stats-grid">{[['المؤكدون حضورهم',data.rsvps.filter(x=>x.attending).length],['مجموع الأشخاص',total],['المعتذرون',data.rsvps.filter(x=>!x.attending).length],['التهاني',data.wishes.length],['بانتظار الموافقة',data.wishes.filter(x=>x.status==='pending').length]].map(([label,value])=><article key={label} className="stat-card"><span>{label}</span><strong>{value}</strong></article>)}</div><div className="admin-panel overview-panel"><Icon name="heart" size={32}/><h3>{settings.firstName} و {settings.secondName}</h3><p>كل التفاصيل الجميلة، في مكان واحد.</p><p>تنعكس التعديلات عند فتح الدعوة أو خلال 30 ثانية في الدعوات المفتوحة.</p><a className="primary" href="/" target="_blank">معاينة الدعوة</a></div></>}
  {tab==='settings'&&<form className="admin-panel" onSubmit={saveSettings}><div className="admin-form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}{['cardText','eventText','finalTitle','endingText','rsvpSuccess','rsvpDeclined'].includes(key)?<textarea rows={3} value={String(settings[key as keyof Settings])} maxLength={2000} onChange={ev=>setting(key as keyof Settings,ev.target.value)}/>:<input value={String(settings[key as keyof Settings])} maxLength={2000} onChange={ev=>setting(key as keyof Settings,ev.target.value)} dir={key.includes('English')||key==='monogram'?'ltr':undefined}/>}</label>)}</div><button className="primary" disabled={busy}>حفظ نصوص الدعوة</button></form>}
  {tab==='event'&&<form className="admin-panel" onSubmit={ev=>{ev.preventDefault();run(()=>api('admin/event',event));}}><div className="admin-form-grid"><label>التاريخ<input type="date" required value={event.date} onChange={ev=>setEvent({...event,date:ev.target.value})}/></label><label>اسم اليوم (فارغ ليُحسب تلقائيًا)<input value={event.dayLabel} onChange={ev=>setEvent({...event,dayLabel:ev.target.value})}/></label><label>موعد الرجال<input type="time" required value={event.reception} onChange={ev=>setEvent({...event,reception:ev.target.value})}/></label><label>موعد النساء<input type="time" required value={event.start} onChange={ev=>setEvent({...event,start:ev.target.value})}/></label><label>المنطقة الزمنية<select value={event.timezone} onChange={ev=>setEvent({...event,timezone:ev.target.value})}>{['+00:00','+01:00','+02:00','+03:00','+04:00','+05:00','-04:00','-05:00','-07:00','-08:00'].map(x=><option key={x} value={x}>UTC {x}</option>)}</select></label></div><p>يُحسب العد التنازلي من تاريخ الحفل وموعد النساء والمنطقة الزمنية.</p><button className="primary" disabled={busy}>حفظ التاريخ والوقت</button></form>}
  {tab==='location'&&<form className="admin-panel" onSubmit={saveSettings}><label className="toggle"><input type="checkbox" checked={settings.showLocation} onChange={ev=>setting('showLocation',ev.target.checked)}/>إظهار قسم الموقع</label><label>عنوان المكان<input value={settings.locationTitle} onChange={ev=>setting('locationTitle',ev.target.value)}/></label><label>وصف المكان<textarea value={settings.locationDescription} onChange={ev=>setting('locationDescription',ev.target.value)}/></label><label>رابط Google Maps<input type="url" dir="ltr" placeholder="https://maps.app.goo.gl/..." value={settings.mapsUrl} onChange={ev=>setting('mapsUrl',ev.target.value)}/></label><button className="primary" disabled={busy}>حفظ الموقع</button><div className="media-editor"><h3>صورة المكان</h3>{settings.locationImage&&<><img src={settings.locationImage} alt="معاينة المكان" width="400" height="260"/><button type="button" className="danger" disabled={busy} onClick={()=>run(()=>api('admin/settings',{locationImage:''}),'تم حذف الصورة')}>حذف الصورة</button></>}<label>رفع صورة (JPEG / PNG / WebP، حتى 10MB)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={ev=>{const file=ev.target.files?.[0];if(file)run(()=>upload(file,'image','location'),'تم رفع صورة المكان');ev.target.value='';}}/></label></div></form>}
  {tab==='music'&&<form className="admin-panel" onSubmit={saveSettings}><label className="toggle"><input type="checkbox" checked={settings.musicEnabled} onChange={ev=>setting('musicEnabled',ev.target.checked)}/>تفعيل الموسيقى الخلفية</label><label className="toggle"><input type="checkbox" checked={settings.musicLoop} onChange={ev=>setting('musicLoop',ev.target.checked)}/>تكرار المقطع</label><button className="primary" disabled={busy}>حفظ إعدادات الموسيقى</button><div className="media-editor"><h3>المقطع الموسيقي</h3>{settings.musicUrl?<><audio key={settings.musicUrl} controls src={settings.musicUrl} preload="metadata"/><button type="button" className="danger" disabled={busy} onClick={()=>run(()=>api('admin/settings',{musicUrl:''}),'تم حذف المقطع')}>حذف المقطع</button></>:<p>لم يُرفع مقطع موسيقي بعد</p>}<label>تغيير الأغنية — رفع MP3 (حتى 15MB)<input type="file" accept="audio/mpeg,.mp3" disabled={busy} onChange={ev=>{const file=ev.target.files?.[0];if(file)run(()=>upload(file,'music'),'تم رفع الموسيقى');ev.target.value='';}}/></label><p>تبدأ الموسيقى بعد ضغط الضيف على «افتح الدعوة».</p></div></form>}
  {tab==='gallery'&&<div className="admin-panel"><label className="toggle"><input type="checkbox" checked={settings.showGallery} disabled={busy} onChange={ev=>{const value=ev.target.checked,previous=settings.showGallery;setting('showGallery',value);run(async()=>{try{await api('admin/settings',{showGallery:value});}catch(err){setting('showGallery',previous);throw err;}});}}/>إظهار قسم الصور في الدعوة</label><div className="upload-zone" onDragOver={ev=>ev.preventDefault()} onDrop={ev=>{ev.preventDefault();const files=Array.from(ev.dataTransfer.files).filter(file=>file.type.startsWith('image/'));if(files.length)run(async()=>{for(const file of files)await upload(file,'image');},'تم رفع الصور');}}><Icon name="heart" size={32}/><p>اسحب الصور هنا أو اخترها من جهازك</p><input ref={fileInput} type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} aria-label="رفع صور الحفل" onChange={ev=>{const files=Array.from(ev.target.files||[]);if(files.length)run(async()=>{for(const file of files)await upload(file,'image');},'تم رفع الصور');ev.target.value='';}}/><span>حتى 10MB للصورة. اسحب الصور لترتيبها أو استخدم الأزرار.</span></div><div className="admin-gallery">{data.gallery.map((image,i)=><article key={image.id} draggable={!busy} onDragStart={()=>setDrag(image.id)} onDragOver={ev=>ev.preventDefault()} onDrop={ev=>{ev.preventDefault();dropImage(image.id);}}><img src={image.url} alt={image.alt} width="320" height="240"/><label>وصف الصورة<input key={image.alt} defaultValue={image.alt} maxLength={200} onBlur={ev=>{if(ev.target.value!==image.alt)run(()=>api('admin/gallery',{action:'alt',id:image.id,alt:ev.target.value}));}}/></label><div className="image-actions"><button disabled={busy||i===0} onClick={()=>reorder(image.id,-1)} aria-label="تقديم الصورة">↑</button><button disabled={busy||i===data.gallery.length-1} onClick={()=>reorder(image.id,1)} aria-label="تأخير الصورة">↓</button><button disabled={busy} className={image.is_cover?'is-cover':''} onClick={()=>run(()=>api('admin/gallery',{action:'cover',id:image.id}),'تم تحديد الغلاف')}>{image.is_cover?'الغلاف ✓':'تعيين غلاف'}</button><button disabled={busy} className="danger" onClick={()=>{if(confirm('حذف الصورة؟'))run(()=>api('admin/gallery',{action:'delete',id:image.id}),'تم حذف الصورة');}}>حذف</button></div></article>)}</div>{!data.gallery.length&&<p>لا توجد صور بعد.</p>}</div>}
  {tab==='rsvp'&&<div className="admin-panel"><div className="table-controls"><label>الحالة<select value={filter} onChange={ev=>setFilter(ev.target.value)}><option value="all">الكل</option><option value="yes">سيحضر</option><option value="no">معتذر</option></select></label><strong>إجمالي الأشخاص المؤكدين: {total}</strong></div><div className="table-scroll"><table><thead><tr>{['الاسم','الأشخاص','الحالة','التاريخ','إجراء'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.rsvps.filter(x=>filter==='all'||(filter==='yes'?!!x.attending:!x.attending)).map(row=><tr key={row.id}><td>{row.name}</td><td>{row.guests}</td><td><span className={`badge ${row.attending?'approved':'rejected'}`}>{row.attending?'سيحضر':'معتذر'}</span></td><td>{date(row.created_at)}</td><td><button className="danger" disabled={busy} onClick={()=>{if(confirm('حذف الرد؟'))run(()=>api('admin/rsvp',{id:row.id}),'تم حذف الرد');}}>حذف</button></td></tr>)}</tbody></table></div>{!data.rsvps.length&&<p>لم تصل ردود حضور بعد.</p>}</div>}
  {tab==='wishes'&&<div className="admin-panel"><label className="toggle"><input type="checkbox" checked={settings.moderation} disabled={busy} onChange={ev=>{const value=ev.target.checked,previous=settings.moderation;setting('moderation',value);run(async()=>{try{await api('admin/settings',{moderation:value});}catch(err){setting('moderation',previous);throw err;}});}}/>تتطلب التهاني الجديدة موافقة قبل النشر</label><div className="admin-wishes">{data.wishes.map(wish=><article key={wish.id}><header><strong>{wish.name}</strong><span className={`badge ${wish.status}`}>{wish.status==='approved'?'مقبولة':wish.status==='pending'?'بانتظار الموافقة':'مرفوضة'}</span></header><p>{wish.message}</p><time>{date(wish.created_at)}</time><footer><button disabled={busy||wish.status==='approved'} onClick={()=>run(()=>api('admin/wishes',{action:'approved',id:wish.id}),'تم قبول التهنئة')}>موافقة</button><button disabled={busy||wish.status==='rejected'} onClick={()=>run(()=>api('admin/wishes',{action:'rejected',id:wish.id}),'تم رفض التهنئة')}>رفض</button><button className="danger" disabled={busy} onClick={()=>{if(confirm('حذف التهنئة؟'))run(()=>api('admin/wishes',{action:'delete',id:wish.id}),'تم حذف التهنئة');}}>حذف</button></footer></article>)}</div>{!data.wishes.length&&<p>لم تصل تهانٍ بعد.</p>}</div>}
  {tab==='appearance'&&<form className="admin-panel" onSubmit={saveSettings}><div className="color-settings">{([['burgundy','الخمري الرئيسي'],['gold','الذهبي'],['ivory','العاجي']] as const).map(([key,label])=><label key={key}>{label}<div><input type="color" value={settings[key]} onChange={ev=>setting(key,ev.target.value)}/><input dir="ltr" value={settings[key]} pattern="#[0-9A-Fa-f]{6}" onChange={ev=>setting(key,ev.target.value)}/></div></label>)}</div><div className="theme-preview" style={{background:settings.ivory,color:settings.burgundy,borderColor:settings.gold}}><span style={{color:settings.gold}}>❧</span><h3>{settings.firstName} و {settings.secondName}</h3><p>{settings.occasion}</p></div><button className="primary" disabled={busy}>حفظ الألوان</button><button type="button" className="admin-secondary" onClick={()=>setSettings({...settings,burgundy:defaults.burgundy,gold:defaults.gold,ivory:defaults.ivory})}>الألوان الافتراضية</button></form>}
  </>}</section></main>;
}
