'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { CSSProperties, FormEvent, ReactNode } from 'react';
import { type PublicData, type Settings, type EventDetails, eventInstant } from '@/lib/defaults';
import Icon from './Icon';
function Flowers({position='tl',large=false}:{position?:string;large?:boolean}){return <img src="/assets/floral-corner.webp" width="800" height="800" alt="" aria-hidden="true" className={`flowers ${position} ${large?'large':''}`} loading={large?'eager':'lazy'}/>}
function Ornament(){return <div className="ornament" aria-hidden="true"><span/><Icon name="leaf" size={30}/><span/></div>}
function Names({s,small=false}:{s:Settings;small?:boolean}){return <div className={`names ${small?'small':''}`}><span>{s.firstName}</span><em>و</em><span>{s.secondName}</span></div>}
function EnglishNames({s}:{s:Settings}){return <p className="english-names" dir="ltr">{s.firstEnglish} &amp; {s.secondEnglish}</p>}
function PaperSection({children,className='',id}:{children:ReactNode;className?:string;id?:string}) {
 const ref=useRef<HTMLElement>(null);
 useEffect(()=>{const element=ref.current;if(!element)return;const observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){element.classList.add('revealed');observer.disconnect();}},{threshold:0.12});observer.observe(element);return()=>observer.disconnect();},[]);
 return <section ref={ref} id={id} className={`paper-section ${className}`}><Flowers/><Flowers position="br"/><div className="section-content">{children}</div></section>;
}
function CountDown({event,title,finished}:{event:EventDetails;title:string;finished:string}) {
 const [remaining,setRemaining]=useState<number|null>(null);
 useEffect(()=>{const update=()=>setRemaining(Math.max(0,eventInstant(event).getTime()-Date.now()));update();const interval=setInterval(update,1000);return()=>clearInterval(interval);},[event]);
 const seconds=Math.floor((remaining||0)/1000);const values=[Math.floor(seconds/86400),Math.floor(seconds/3600)%24,Math.floor(seconds/60)%60,seconds%60];
 return <><Icon name="leaf" size={32}/><h2>{title}</h2>{remaining===0?<p className="finished">{finished}</p>:<div className="countdown" aria-label="الوقت المتبقي" dir="rtl">{values.map((value,i)=><div key={i}><strong>{remaining===null?'—':String(value).padStart(2,'0')}</strong><span>{['يوم','ساعة','دقيقة','ثانية'][i]}</span></div>)}</div>}</>;
}
function timeLabel(time:string){const [h,m]=time.split(':').map(Number);return `${h%12||12}:${String(m).padStart(2,'0')} ${h>=12?'مساءً':'صباحًا'}`;}
async function send(path:string,body:unknown){const res=await fetch(`/api/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'تعذر الإرسال');return data;}
export default function Invitation({initial}:{initial:PublicData}) {
 const [data,setData]=useState(initial),[phase,setPhase]=useState<'closed'|'opening'|'open'>('closed');
 const [playing,setPlaying]=useState(false),[volume,setVolume]=useState(0.35),[musicNotice,setMusicNotice]=useState('');
 const [menu,setMenu]=useState(false),[message,setMessage]=useState(''),[index,setIndex]=useState(0);
 const [rsvpStatus,setRsvpStatus]=useState(''),[wishStatus,setWishStatus]=useState(''),[rsvpError,setRsvpError]=useState(''),[wishError,setWishError]=useState('');
 const [attending,setAttending]=useState(true),[sendingRsvp,setSendingRsvp]=useState(false),[sendingWish,setSendingWish]=useState(false);
 const audio=useRef<HTMLAudioElement>(null),intro=useRef<HTMLElement>(null),swipe=useRef<number|null>(null),timers=useRef<ReturnType<typeof setTimeout>[]>([]);
 const s=data.settings,e=data.event;
 useEffect(()=>{const refresh=()=>fetch('/api/public').then(r=>r.json()).then(setData).catch(()=>{});window.addEventListener('focus',refresh);const interval=setInterval(refresh,30000);return()=>{window.removeEventListener('focus',refresh);clearInterval(interval);timers.current.forEach(clearTimeout);};},[]);
 useEffect(()=>{if(audio.current)audio.current.volume=volume;},[volume]);
 useEffect(()=>{if(!s.musicEnabled){audio.current?.pause();setPlaying(false);}},[s.musicEnabled]);
 useEffect(()=>{document.title=`${s.firstName} و ${s.secondName} | ${s.occasion}`;},[s.firstName,s.secondName,s.occasion]);
 const startMusic=useCallback(()=>{if(audio.current&&s.musicEnabled&&s.musicUrl){audio.current.volume=volume;audio.current.play().then(()=>{setPlaying(true);setMusicNotice('');}).catch(()=>setMusicNotice('اضغط زر الموسيقى للتشغيل'));}},[s.musicEnabled,s.musicUrl,volume]);
 function openInvitation(){if(phase!=='closed')return;setPhase('opening');startMusic();const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;timers.current.push(setTimeout(()=>{setPhase('open');window.scrollTo({top:0,behavior:'instant'});},reduced?120:2450));}
 function toggleMusic(){if(playing){audio.current?.pause();setPlaying(false);}else startMusic();}
 async function submitRsvp(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);setSendingRsvp(true);setRsvpError('');try{await send('rsvp',{name:fields.get('name'),guests:Number(fields.get('guests')),attending,website:fields.get('website')});setRsvpStatus(attending?s.rsvpSuccess:s.rsvpDeclined);}catch(error){setRsvpError((error as Error).message);}finally{setSendingRsvp(false);}}
 async function submitWish(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const fields=new FormData(form);setSendingWish(true);setWishError('');try{const result=await send('wishes',{name:fields.get('name'),message:fields.get('message'),website:fields.get('website')});setWishStatus(result.pending?'شكرًا لك، ستظهر تهنئتك بعد الموافقة عليها':'شكرًا لك، أضفت لفرحتنا كلمة جميلة');form.reset();const fresh=await fetch('/api/public').then(r=>r.json());setData(fresh);}catch(error){setWishError((error as Error).message);}finally{setSendingWish(false);}}
 function notify(text:string){setMessage(text);timers.current.push(setTimeout(()=>setMessage(''),3500));}
 async function copyLink(){try{await navigator.clipboard.writeText(window.location.href);notify('تم نسخ رابط الدعوة');}catch{notify('تعذر النسخ، يمكنك نسخ الرابط من شريط العنوان');}}
 async function share(){if(navigator.share){try{await navigator.share({title:`${s.firstName} و ${s.secondName}`,text:s.occasion,url:window.location.href});}catch(error){if((error as Error).name!=='AbortError')copyLink();}}else copyLink();}
 const day=e.dayLabel||new Intl.DateTimeFormat('ar',{weekday:'long',timeZone:'UTC'}).format(new Date(e.date+'T12:00:00Z'));
 const date=new Intl.DateTimeFormat('ar',{day:'numeric',month:'long',year:'numeric',numberingSystem:'latn',timeZone:'UTC'}).format(new Date(e.date+'T12:00:00Z'));
 const gallery=data.gallery;const activeIndex=gallery.length?index%gallery.length:0;
 function changeImage(direction:number){setIndex(old=>(old+direction+gallery.length)%gallery.length);}
 const theme={'--burgundy':s.burgundy,'--gold':s.gold,'--ivory':s.ivory} as CSSProperties;
 return <main className="invitation-world" style={theme}>
  <div className="desktop-bloom left" aria-hidden="true"><Flowers large/></div><div className="desktop-bloom right" aria-hidden="true"><Flowers large/></div>
  <div className="invitation-shell">
    <audio ref={audio} src={s.musicUrl||undefined} loop={s.musicLoop} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onError={()=>{setPlaying(false);setMusicNotice('تعذر تشغيل الملف الصوتي')}}/>
    {phase!=='open'?<section ref={intro} className={`intro ${phase}`} aria-label="فتح الدعوة" onPointerMove={event=>{if(phase==='closed'&&intro.current&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const rect=event.currentTarget.getBoundingClientRect();intro.current.style.setProperty('--px',`${(event.clientX-rect.left-rect.width/2)/45}px`);intro.current.style.setProperty('--py',`${(event.clientY-rect.top-rect.height/2)/60}px`);}}}>
      <div className="intro-grain"/><div className="light-beam"/><div className="petals" aria-hidden="true">{Array.from({length:7},(_,i)=><i key={i} style={{'--i':i} as CSSProperties}>❧</i>)}</div>
      <header className="intro-brand"><div className="monogram" dir="ltr">{s.monogram}</div><EnglishNames s={s}/><span className="brand-line"/></header>
      <div className="envelope-scene">
        <Flowers large/><Flowers large position="br"/>
        <div className="envelope"><div className="envelope-back"/><div className="insert-card"><span className="insert-bismillah">﷽</span><Names s={s} small/><EnglishNames s={s}/></div><div className="envelope-front"/><div className="envelope-flap"/><div className="wax-seal"><Icon name="leaf" size={28}/></div><span className="envelope-thread"/></div>
      </div>
      <div className="intro-copy"><h1>{s.introTitle}</h1><p>{s.introText}</p><button className="primary intro-button" onClick={openInvitation} disabled={phase==='opening'}><span>{phase==='opening'?'بكل حب…':s.openLabel}</span><Icon name="heart" size={23}/></button></div>
      <p className="intro-foot" dir="ltr">WITH LOVE, FOR YOU</p>
    </section>:<div className="invitation-pages">
      <div className="guest-toolbar">
       {s.musicEnabled&&s.musicUrl&&<div className="music-controls"><button className={`round-button music-button ${playing?'playing':''}`} aria-label={playing?'إيقاف الموسيقى':'تشغيل الموسيقى'} aria-pressed={playing} onClick={toggleMusic}><Icon name={playing?'pause':'music'} size={20}/></button><div className="volume-control"><label htmlFor="music-volume">الصوت</label><input id="music-volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={event=>setVolume(Number(event.target.value))}/></div></div>}
       <button className="round-button menu-button" aria-label="أقسام الدعوة" aria-expanded={menu} onClick={()=>setMenu(!menu)}><Icon name="menu" size={22}/></button>
       {menu&&<nav className="guest-menu" aria-label="أقسام الدعوة">{[['details',s.occasion],['rsvp','تأكيد الحضور'],['wishes','التهاني'],...(s.showGallery?[['gallery',s.galleryTitle]]:[])] .map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</nav>}
      </div>
      {musicNotice&&<p className="music-notice" role="status">{musicNotice}</p>}
      <PaperSection className="reveal-card" id="invitation">
        <p className={`bismillah ${s.bismillah==='بسم الله الرحمن الرحيم'?'calligraphic':''}`} aria-label={s.bismillah}>{s.bismillah==='بسم الله الرحمن الرحيم'?'﷽':s.bismillah}</p>
        <p className="card-intro">{s.cardText}</p>
        <div className="name-reveal"><div className="name-center"><Names s={s}/><EnglishNames s={s}/></div><div className="name-panel right"><span>❧</span></div><div className="name-panel left"><span>❧</span></div></div>
        <Ornament/><p className="card-foot">{s.occasion}</p><a href="#details" className="scroll-cue" aria-label="تفاصيل الحفل"><span>التفاصيل</span><Icon name="chevron" size={16}/></a>
      </PaperSection>
      <PaperSection className="event-section" id="details"><Icon name="leaf" size={32}/><h2>{s.occasion}</h2><p className="event-copy">{s.eventText}</p><Ornament/><div className="event-date"><Icon name="calendar" size={31}/><span>{day}</span><strong>{date}</strong></div><div className="event-times"><div><Icon name="clock" size={31}/><span>{s.menLabel}</span><strong dir="auto">{timeLabel(e.reception)}</strong></div><div><Icon name="rings" size={34}/><span>{s.womenLabel}</span><strong dir="auto">{timeLabel(e.start)}</strong></div></div></PaperSection>
      <PaperSection className="countdown-section" id="countdown"><CountDown event={e} title={s.countdownTitle} finished={s.countdownFinished}/></PaperSection>
      {s.showLocation&&<PaperSection className="location-section" id="location">{s.locationImage&&<img className="location-image" src={s.locationImage} alt={s.locationTitle} width="800" height="560" loading="lazy"/>}<Icon name="pin" size={32}/><h2>{s.locationTitle}</h2>{s.locationDescription&&<p>{s.locationDescription}</p>}{s.mapsUrl?<a className="primary" href={s.mapsUrl} target="_blank" rel="noopener noreferrer"><Icon name="pin" size={19}/><span>فتح الموقع على الخريطة</span></a>:<p className="quiet-location">سنشارككم تفاصيل المكان قريبًا</p>}</PaperSection>}
      <PaperSection className="rsvp-section" id="rsvp"><Icon name="leaf" size={32}/><h2>{s.rsvpTitle}</h2><p>{s.rsvpSubtitle}</p>{rsvpStatus?<div className="success-state" role="status"><Icon name="heart" size={34}/><p>{rsvpStatus}</p><button className="text-button" onClick={()=>setRsvpStatus('')}>تعديل الرد</button></div>:<form onSubmit={submitRsvp} className="guest-form"><label htmlFor="guest-name">الاسم<input id="guest-name" name="name" autoComplete="name" minLength={2} maxLength={100} required placeholder="اسمكم الكريم"/></label><label htmlFor="guest-count">عدد الأشخاص<input id="guest-count" name="guests" type="number" min="1" max="20" defaultValue="1" required/></label><label className="honeypot" aria-hidden="true">اترك فارغًا<input name="website" tabIndex={-1} autoComplete="off"/></label><fieldset className="attendance"><legend>تأكيد المشاركة</legend><label className={attending?'selected':''}><input type="radio" name="attendance" checked={attending} onChange={()=>setAttending(true)}/><Icon name="check" size={21}/><span>سأحضر</span></label><label className={!attending?'selected':''}><input type="radio" name="attendance" checked={!attending} onChange={()=>setAttending(false)}/><span className="decline-icon">×</span><span>أعتذر عن الحضور</span></label></fieldset>{rsvpError&&<p className="form-error" role="alert">{rsvpError}</p>}<button className="primary" disabled={sendingRsvp}><Icon name="heart" size={20}/>{sendingRsvp?'جارٍ التأكيد…':'تأكيد الحضور'}</button></form>}</PaperSection>
      <PaperSection className="wishes-section" id="wishes"><Icon name="leaf" size={32}/><h2>{s.wishesTitle}</h2><p>{s.wishesSubtitle}</p><form onSubmit={submitWish} className="guest-form"><label htmlFor="wish-name">الاسم<input id="wish-name" name="name" placeholder="اسمكم الكريم" minLength={2} maxLength={100} required autoComplete="name"/></label><label htmlFor="wish-message">التهنئة<textarea id="wish-message" name="message" placeholder="اكتب تهنئتك هنا..." minLength={2} maxLength={1000} rows={3} required/></label><label className="honeypot" aria-hidden="true">اترك فارغًا<input name="website" tabIndex={-1} autoComplete="off"/></label>{wishError&&<p className="form-error" role="alert">{wishError}</p>}{wishStatus&&<p className="form-success" role="status">{wishStatus}</p>}<button className="primary" disabled={sendingWish}><Icon name="heart" size={20}/>{sendingWish?'جارٍ الإرسال…':'إرسال التهنئة'}</button></form><div className="wish-list">{data.wishes.slice(0,6).map(wish=><article className="wish-card" key={wish.id}><strong>{wish.name}</strong><p>{wish.message}</p><footer><time dateTime={wish.created_at}>{new Intl.DateTimeFormat('ar',{day:'numeric',month:'short'}).format(new Date(wish.created_at))}</time><Icon name="heart" size={16}/></footer></article>)}</div></PaperSection>
      {s.showGallery&&<PaperSection className="gallery-section" id="gallery"><Icon name="leaf" size={32}/><h2>{s.galleryTitle}</h2>{gallery.length?<div className="gallery"><div className="gallery-stage" onTouchStart={event=>swipe.current=event.touches[0].clientX} onTouchEnd={event=>{if(swipe.current!==null){const delta=event.changedTouches[0].clientX-swipe.current;if(Math.abs(delta)>40)changeImage(delta>0?1:-1);swipe.current=null;}}}><img key={gallery[activeIndex].id} src={gallery[activeIndex].url} alt={gallery[activeIndex].alt} width="800" height="1000" loading="lazy"/><button className="gallery-prev round-button" onClick={()=>changeImage(-1)} aria-label="الصورة السابقة"><Icon name="chevron"/></button><button className="gallery-next round-button" onClick={()=>changeImage(1)} aria-label="الصورة التالية"><Icon name="chevron"/></button><span className="image-count" aria-live="polite">{activeIndex+1} / {gallery.length}</span></div><div className="thumbnails">{gallery.map((image,i)=><button key={image.id} onClick={()=>setIndex(i)} className={i===activeIndex?'active':''} aria-label={`عرض الصورة ${i+1}`} aria-pressed={i===activeIndex}><img src={image.url} alt={image.alt} width="120" height="150" loading="lazy"/></button>)}</div></div>:<div className="gallery-empty"><Icon name="heart" size={36}/><p>هنا سنحتفظ بلحظاتنا الجميلة</p><span>صور الحفل قريبًا</span></div>}</PaperSection>}
      <PaperSection className="final-card" id="with-love"><Icon name="leaf" size={32}/><h2>{s.finalTitle}</h2><span className="gold-heart"><Icon name="heart" size={21}/></span><Names s={s}/><EnglishNames s={s}/><div className="final-actions"><a href="/api/calendar"><Icon name="calendar"/><span>إضافة إلى التقويم</span></a><button onClick={share}><Icon name="share"/><span>مشاركة الدعوة</span></button><button onClick={copyLink}><Icon name="copy"/><span>نسخ الرابط</span></button></div><Ornament/><p>{s.finalText}</p></PaperSection>
      <section className="cinematic-ending"><div className="bokeh" aria-hidden="true"/><Flowers position="br" large/><div className="ending-copy"><p>{s.endingText}</p><Icon name="heart" size={22}/><Ornament/><EnglishNames s={s}/></div></section>
    </div>}
  </div>{message&&<div className="toast" role="status">{message}</div>}
 </main>;
}
