create table if not exists public.settings (
  id integer primary key check (id = 1),
  value jsonb not null default '{}'::jsonb
);

create table if not exists public.event_details (
  id integer primary key check (id = 1),
  value jsonb not null default '{}'::jsonb
);

create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  name text not null,
  guests integer not null check (guests between 1 and 20),
  attending smallint not null check (attending in (0,1)),
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  status text not null check (status in ('pending','approved','rejected')),
  fingerprint text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  url text not null,
  alt text not null,
  position integer not null default 0,
  is_cover smallint not null default 0
);

create table if not exists public.media (
  id bigint generated by default as identity primary key,
  url text not null unique,
  kind text not null,
  original_name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  token_hash text primary key,
  expires bigint not null
);

create table if not exists public.rate_limits (
  key text primary key,
  count integer not null,
  reset_at bigint not null
);

insert into public.settings (id,value)
values (1,'{}'::jsonb)
on conflict (id) do nothing;

insert into public.event_details (id,value)
values (1,'{}'::jsonb)
on conflict (id) do nothing;

create index if not exists rsvps_created_at_idx
on public.rsvps(created_at desc);

create index if not exists wishes_created_at_idx
on public.wishes(created_at desc);

alter table public.settings enable row level security;
alter table public.event_details enable row level security;
alter table public.rsvps enable row level security;
alter table public.wishes enable row level security;
alter table public.gallery enable row level security;
alter table public.media enable row level security;
alter table public.sessions enable row level security;
alter table public.rate_limits enable row level security;

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'invitation-media',
  'invitation-media',
  false,
  15728640,
  array['image/jpeg','image/png','image/webp','audio/mpeg']
)
on conflict (id) do nothing;